name: biparsing
version: 0.0.0.1

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - mtl
  - mono-traversable
  - transformers
  - lens

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - PatternSynonyms
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

library:
  source-dirs: src/
  dependencies:
    - profunctors
    - extra
    - data-diverse
    - safe
    - generic-data
    - data-default
    - hvect
  other-modules:
    - Prelude
    #- Paths_biparsing
  ghc-options:
    #- -Werror
    - -Weverything

    - -Wno-missing-kind-signatures
    - -Wno-missing-safe-haskell-mode
    - -Wno-implicit-prelude
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-missing-deriving-strategies
    - -Wno-missing-local-signatures

    - -Wno-unused-packages

    #- -fdefer-type-errors

tests:
  spec:
    main: Spec.hs
    source-dirs: tests/
    dependencies:
      - biparsing
      - hspec
      - hspec-discover
      - QuickCheck
      - quickcheck-instances
      - text
      - bytestring
      - containers
      - vector
      - generic-random
      - generic-deriving
    default-extensions:
      - OverloadedStrings
      - OverloadedLists
      - NamedFieldPuns
    ghc-options:
      - -Werror
      - -Weverything
      - -fprint-potential-instances

      - -Wno-missing-kind-signatures
      - -Wno-missing-safe-haskell-mode
      - -Wno-implicit-prelude
      - -Wno-safe
      - -Wno-unsafe
      - -Wno-missing-deriving-strategies
      - -Wno-missing-local-signatures
      - -Wno-missing-import-lists
      - -Wno-missing-export-lists
      - -Wno-incomplete-uni-patterns
      - -Wno-orphans

      - -Wno-unused-packages

