name: biparsing
version: 0.0.0.1

dependencies:
  - base >=4.10 && < 5
  - transformers
  - mono-traversable

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - ImportQualifiedPost
  - LambdaCase
  - RankNTypes
  - RecordWildCards
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - ScopedTypeVariables
  - MultiParamTypeClasses
  - FunctionalDependencies
  - StandaloneKindSignatures
  - DuplicateRecordFields

library:
  source-dirs: src/
  dependencies:
    - base >=4.10 && < 5
    #- string-conversions
    - profunctors
    - monad-loops
    - template-haskell
    - monad-loops
    - extra
    - bifunctors
  default-extensions:
    - NoImplicitPrelude
  ghc-options:
    #- -Werror
    - -Weverything

    - -Wno-missing-kind-signatures
    - -Wno-missing-safe-haskell-mode
    - -Wno-implicit-prelude
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-missing-deriving-strategies
    - -Wno-missing-local-signatures

tests:
  spec:
    main: Spec.hs
    source-dirs: tests/
    dependencies:
      - biparsing
      - hspec
      - hspec-discover
      - QuickCheck
      - quickcheck-instances
      - text
      - bytestring
      - containers
      - vector
    default-extensions:
      - OverloadedStrings
      - OverloadedLists

