name: biparsing
version: 0.0.0.1

dependencies:
  - base >=4.10 && < 5
  - microlens
  - transformers
  - generic-functor
  - generic-monoid
  - barbies

default-extensions:
  - DeriveGeneric
  - DerivingVia
  - DeriveFunctor
  - LambdaCase
  - BlockArguments

executable:
  main: app/Main.hs
  dependencies:
    - biparsing

library:
  source-dirs: src/
