resolver: lts-20.24

extra-deps:
  - github: BebeSparkelSparkel/mono-traversable
    commit: c302c973de6090656177cc27cc62e3fb83118af3
    subdirs:
      - mono-traversable
  #- ../mono-traversable/mono-traversable
