cabal-version: 2.2
name: biparsing-binary
version: 0.0.0.1
synopsis: Combinators for working with binary data typically ByteString.
category: Parsing
homepage: https://github.com/BebeSparkelSparkel/biparsing
author: William Rusnack
maintainer: William Rusnack
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple

flag padantic
  description: -Werror -Weverything
  default: False

library
  -- cabal-gild: discover src --exclude=src/Prelude.hs
  exposed-modules:
    Biparse.Binary
    Biparse.Binary.Generics

  other-modules:
    Prelude

  hs-source-dirs:
    src/

  default-extensions:
    BlockArguments
    DeriveGeneric
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    LambdaCase
    MultiParamTypeClasses
    PatternSynonyms
    RankNTypes
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators

  if flag(padantic)
    ghc-options:
      -Werror
      -Weverything
      -Wno-implicit-prelude
      -Wno-missing-deriving-strategies
      -Wno-missing-kind-signatures
      -Wno-missing-local-signatures
      -Wno-missing-safe-haskell-mode
      -Wno-safe
      -Wno-unsafe
      -Wno-unused-packages
  build-depends:
    base,
    biparsing-combinators,
    biparsing-core,
    mtl,
    profunctors,
    wide-word,

  mixins:
    base hiding (Prelude)

  default-language: Haskell2010

test-suite spec
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  -- cabal-gild: discover tests --exclude=tests/Spec.hs
  other-modules:
    Biparse.Binary.GenericsSpec
    Biparse.BinarySpec

  hs-source-dirs:
    tests/

  default-extensions:
    BlockArguments
    DeriveGeneric
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    LambdaCase
    MultiParamTypeClasses
    OverloadedLists
    PatternSynonyms
    RankNTypes
    ScopedTypeVariables
    StandaloneKindSignatures
    TypeApplications
    TypeFamilies
    TypeOperators

  if flag(padantic)
    ghc-options:
      -Werror
      -Weverything
      -fprint-potential-instances
      -Wno-implicit-prelude
      -Wno-incomplete-uni-patterns
      -Wno-missing-deriving-strategies
      -Wno-missing-export-lists
      -Wno-missing-import-lists
      -Wno-missing-kind-signatures
      -Wno-missing-local-signatures
      -Wno-missing-safe-haskell-mode
      -Wno-orphans
      -Wno-safe
      -Wno-unsafe
      -Wno-unused-packages
  build-tool-depends:
    hspec-discover:hspec-discover

  build-depends:
    base,
    binary,
    biparsing-binary,
    biparsing-core,
    biparsing-test,
    bytestring,
    hspec,
    quickcheck-instances,
    wide-word,

  mixins:
    base hiding (Prelude)

  default-language: Haskell2010
