name: biparsing-test
version: 0.0.0.1
synopsis: Test Prelude for the biparsing suite.
homepage: https://github.com/BebeSparkelSparkel/biparsing
category: Parsing
author: William Rusnack
license: BSD-3-Clause
license-file: LICENSE

spec-version: 0.36.0

library:
  exposed-modules: Prelude
  source-dirs: .
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - QuickCheck
    - safe
    - biparsing-core
    - biparsing-core
    - biparsing-text
    - biparsing-text
    - bytestring
    - containers
    - data-default
    - hspec
    - mono-traversable
    - microlens
    - mtl
    - quickcheck-instances
    - semigroupoids
    - text
    - transformers
    - vector
  ghc-options:
    - -Werror
    - -Weverything

    - -Wno-unused-packages
