name: examples
version: 0.0.0.1
synopsis: Biparsing Examples
homepage: https://github.com/BebeSparkelSparkel/biparsing
category: Parsing
author: William Rusnack
license: BSD-3-Clause
license-file: LICENSE
spec-version: 0.36.0

dependencies:
  - base
  - biparsing-mixes

ghc-options:
  - -Weverything
  - -Wno-missing-import-lists
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures

executables:
  ADT:
    main: ADT.hs
    dependencies:
      - bytestring
      - microlens-pro
      - microlens
  ProductAndSum:
    main: ProductAndSum.hs
    dependencies:
      - bytestring
      - extra
  StreamConversion:
    main: StreamConversion.hs
    dependencies:
      - biparsing-core
      - mtl
      - semigroupoids
  WriterState:
    main: WriterState.hs
    dependencies:
      - biparsing-core
      - mono-traversable >= 1.0.17.0
      - microlens-pro
      - microlens
      - text

tests:
  File:
    main: File.hs
    dependencies:
      - biparsing-file
