name: biparsing-text
version: 0.0.0.1
synopsis: Combinators for working with text data typically String, Text, or ByteString.
homepage: https://github.com/BebeSparkelSparkel/biparsing
category: Parsing
author: William Rusnack
license: BSD-3-Clause
license-file: LICENSE

spec-version: 0.36.0

library:
  source-dirs: src/
  other-modules:
    - Prelude
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - biparsing-core
    - mtl
    - mono-traversable
    - semigroupoids
    - safe
    - microlens
    - microlens-th
    - data-default
  default-extensions:
    - ImportQualifiedPost
    - PatternSynonyms
    - RankNTypes
    - TypeApplications
    - ScopedTypeVariables
    - ConstraintKinds
    - TypeFamilies
    - FlexibleContexts
    - BlockArguments
    - LambdaCase
    - StandaloneKindSignatures
    - FlexibleInstances
    - DataKinds
    - MultiParamTypeClasses
    - DeriveFunctor
  ghc-options:
    - -Werror
    - -Weverything

    - -Wno-implicit-prelude
    - -Wno-missing-deriving-strategies
    - -Wno-missing-kind-signatures
    - -Wno-missing-local-signatures
    - -Wno-missing-safe-haskell-mode
    - -Wno-safe
    - -Wno-unsafe

    - -Wno-unused-packages
