name: biparsing-mixes
version: 0.0.0.1
synopsis: Easy to use monad and type mixes for biparsing.
homepage: https://github.com/BebeSparkelSparkel/biparsing
category: Parsing
author: William Rusnack
license: BSD-3-Clause
license-file: LICENSE
spec-version: 0.36.0

default-extensions:
  - ImportQualifiedPost
  - BlockArguments
  - TypeApplications

library:
  source-dirs: src/
  other-modules:
    - Prelude
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - biparsing-core
    - biparsing-text
    - bytestring
    - text >= 2.1.1
    - mono-traversable >= 1.0.17.0
    - transformers >= 0.6.1.1
    - mtl
    - semigroupoids
    - microlens
  default-extensions:
    - DataKinds
    - MultiParamTypeClasses
    - PatternSynonyms
    - StandaloneKindSignatures
    - TypeFamilies
    - UndecidableInstances
    - AllowAmbiguousTypes
    - FlexibleContexts
    - FlexibleInstances
    - RankNTypes
    - ScopedTypeVariables
  ghc-options:
    - -Werror
    - -Weverything

    - -Wno-implicit-prelude
    - -Wno-missing-deriving-strategies
    - -Wno-missing-kind-signatures
    - -Wno-missing-local-signatures
    - -Wno-missing-safe-haskell-mode
    - -Wno-safe
    - -Wno-unsafe

    - -Wno-unused-packages

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs: tests/
    dependencies:
      - biparsing-mixes
      - name: biparsing-test
        mixin:
          - (Prelude as Test.Prelude)
      - hspec
      - data-default
      - template-haskell
    default-extensions:
      - OverloadedStrings
      - TupleSections
    ghc-options:
      - -Werror
      - -Weverything
      - -fprint-potential-instances

      - -Wno-implicit-prelude
      - -Wno-incomplete-uni-patterns
      - -Wno-missing-deriving-strategies
      - -Wno-missing-export-lists
      - -Wno-missing-import-lists
      - -Wno-missing-kind-signatures
      - -Wno-missing-local-signatures
      - -Wno-missing-safe-haskell-mode
      - -Wno-orphans
      - -Wno-safe
      - -Wno-unsafe

      - -Wno-unused-packages
