name: biparsing-text-tests
version: 0.0.0.1
synopsis: Tests for biparsing-text
description: Cabal does not allow circular dependencies for tests in new builds and many of the tests for biparsing-core require biparsing-text which was extracted to its own package.
homepage: https://github.com/BebeSparkelSparkel/biparsing
category: Parsing
author: William Rusnack
license: BSD-3-Clause
license-file: LICENSE

spec-version: 0.36.0

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs: tests/
    dependencies:
      - biparsing-text
      - biparsing-test
      - hspec
      - ghc-prim
    default-extensions:
      - OverloadedStrings
      - BlockArguments
      - TypeApplications
      - RankNTypes
      - LambdaCase
      - ScopedTypeVariables
      - DataKinds
      - KindSignatures
      - FlexibleContexts
      - GeneralizedNewtypeDeriving
    ghc-options:
      - -Werror
      - -Weverything
      - -fprint-potential-instances

      - -Wno-implicit-prelude
      - -Wno-incomplete-uni-patterns
      - -Wno-missing-deriving-strategies
      - -Wno-missing-export-lists
      - -Wno-missing-import-lists
      - -Wno-missing-kind-signatures
      - -Wno-missing-local-signatures
      - -Wno-missing-safe-haskell-mode
      - -Wno-orphans
      - -Wno-safe
      - -Wno-unsafe

      - -Wno-unused-packages
